services:
  web:
    build: .
    image: money-stuff-scheduler
    container_name: money-stuff-scheduler
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
